security:
  users:
    admin:
      username: ${APP_ADMIN_USERNAME:admin}
      password: ${APP_ADMIN_PASSWORD:StrongPass123!}
    viewer:
      username: ${APP_VIEWER_USERNAME:viewer}
      password: ${APP_VIEWER_PASSWORD:StrongPass123!}